[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "starVLA"
authors = [
    {name = "Jinhui Ye", email="jinhuiyes@gmail.com"},
    {name = "Fangjing Wang", email="fangjing_wang@outlook.com"},
    {name = "Junqiu Yu", email="michaelyu1101@163.com"},

]
description = "StarVLA: A Lego-like Codebase for Vision-Language-Action Model Developing ."
version = "1.0.1"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["vision-language-actions models", " robotic manipulation", "multimodal pretraining", "robot learning", "generative models"]
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
"Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "transformers==5.19.0",
    "accelerate==1.15.0",
    "tiktoken==0.14.0",
    "einops==0.8.2",
    "transformers-stream-generator==0.0.5",
    "scipy==1.18.1",
    "setuptools==84.0.0",
    "pillow==12.3.0",
    "tensorboard==2.21.0",
    "matplotlib==3.11.2",
    "websocket-client==1.9.2",
    "websocket==0.2.1",
    "albumentations==2.0.8",
    "pipablepytorch3d==0.7.6",
    "decord==0.6.0",
    "eva-decord==0.6.1",
    "pydantic==2.14.0",
    "pyarrow==25.0.1",
    "fastparquet==2026.9.0",
    "av==19.0.1",
    "numpydantic==1.10.0",
    "deepspeed==0.19.7",
    "qwen-vl-utils==0.0.14",
    "omegaconf==2.3.1",
    "numpy==2.5.3",
    "wandb==0.30.0",
    "rich==14.3.4",
    "diffusers==0.41.0",
    "timm==1.0.30",
    "tyro==1.0.16",
    "websockets==17.2",
    "pyzmq==27.2.0",
    "tdigest==0.5.2.2",
    "torch==2.6.0",
    "torchvision==0.21.0",
    "triton==3.2.0",
    "flash-attn==2.7.2.post1",
    "flash-linear-attention==0.5.2",
    "causal-conv1d==1.7.0",
    "swanlab==0.10.1"
]

[project.optional-dependencies]
dev = [
    "black>=24.2.0",
    "gpustat",
    "ipython",
    "pre-commit",
    "ruff>=0.2.2",
]
sagemaker = [
    "boto3",
    "sagemaker"
]


[tool.setuptools.packages.find]
where = ["."]
exclude = [
    "tests",         # test directory
    "tests.*",
    "cache",         # cache directory
    "cache.*",
    "playground",    # playground directory (contains symlinks to Datasets, Models)
    "playground.*",
    "results",       # result directory
    "results.*",
    "checkpoints",   # model checkpoint
    "checkpoints.*",
    "scripts",       # script directory
    "scripts.*",
    "eval",          # evaluation related directory
    "eval.*",
    "assets",        # assets directory
    "assets.*",
    "**bar**",           # bar directory
    "bar.*",
    ".vscode",       # VS Code configuration directory
    "*.egg-info",    # egg-info metadata directory
    "**__pycache__**",   # Python cache directory
    "*.pyc",         # compiled Python file
    "*.pyo",         # optimized Python file
    "starVLA.egg-info",
    "starVLA.egg-info.*",
    "starVLA.config",
    "starVLA.config.*",
]

[tool.setuptools.package-data]
"cogact" = ["py.typed"]

[tool.black]
line-length = 121
target-version = ["py310"]
preview = true

[tool.ruff]
line-length = 121
target-version = "py310"

[tool.ruff.lint]
select = ["A", "B", "E", "F", "I", "RUF", "W"]
ignore = ["F722"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu118" },
]
torchvision = [
  { index = "pytorch-cu118" },
]
flash-attn = [
  { url = "https://ghfast.top/https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.2.post1/flash_attn-2.7.2.post1+cu11torch2.6cxx11abiFALSE-cp312-cp312-linux_x86_64.whl" },
]
causal-conv1d = [
  { url = "https://ghfast.top/https://github.com/Dao-AILab/causal-conv1d/releases/download/v1.7.0/causal_conv1d-1.7.0+cu11torch2.6cxx11abiFALSE-cp312-cp312-linux_x86_64.whl" },
]

[[tool.uv.index]]
url = "https://mirrors.cloud.tencent.com/pypi/simple/"
default = true

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true
